import { defineStore } from 'pinia';

export const useCatalogStore = defineStore('catalog', {
  state: () => ({
    samplePhotos: [
      {
        id: 1,
        title: 'Afternoon Rainstorm',
        href: '#',
        description:
          'An afternoon rainstorm near the community of Clingman, NC',
        imageUrl: '/samplePhotos/Afternoon rainstorm 1.jpg',
        releaseVersion: '1.0.1',
        creationDate: 'Dec 17, 2023',
        size: '1.2 MB',
      },
      {
        id: 2,
        title: 'Afternoon Rainstorm',
        href: '#',
        description:
          'Another image of an afternoon rainstorm near the community of Clingman, NC',
        imageUrl: '/samplePhotos/Afternoon rainstorm 2.jpg',
        releaseVersion: '1.0.1',
        creationDate: 'Dec 17, 2023',
        size: '2.3 MB',
      },
      {
        id: 3,
        title: 'Dune at Nags Head',
        href: '#',
        description: 'Sand dunes at the coast near Nags Head, NC',
        imageUrl: '/samplePhotos/Dunes at coast 1.jpg',
        releaseVersion: '1.0.1',
        creationDate: 'Dec 17, 2023',
        size: '4.1 MB',
      },
      {
        id: 4,
        title: 'Beach at Nags Head',
        href: '#',
        description: 'The beach along the coast near Nags Head, NC',
        imageUrl: '/samplePhotos/Dunes at coast 2.jpg',
        releaseVersion: '1.0.1',
        creationDate: 'Dec 17, 2023',
        size: '3.9 MB',
      },
      {
        id: 5,
        title: 'Historic plantation houses',
        href: '#',
        description: 'A historic plantation in eastern NC',
        imageUrl: '/samplePhotos/Farm House 2.jpg',
        releaseVersion: '1.0.1',
        creationDate: 'Dec 17, 2023',
        size: '2.7 MB',
      },
      {
        id: 6,
        title: 'Historic plantation buildings',
        href: '#',
        description: 'More house at historic plantation in eastern NC',
        imageUrl: '/samplePhotos/Farm Houses.jpg',
        releaseVersion: '1.0.1',
        creationDate: 'Dec 17, 2023',
        size: '3.6 MB',
      },
      {
        id: 7,
        title: 'Historic plantation lane',
        href: '#',
        description: 'The lane approaching a historic plantation in eastern NC',
        imageUrl: '/samplePhotos/Farm Lane.jpg',
        releaseVersion: '1.0.1',
        creationDate: 'Dec 17, 2023',
        size: '4.2 MB',
      },
      {
        id: 8,
        title: 'Fog in the Morning',
        href: '#',
        description: 'Fog laying low in a field with the foothills of NC',
        imageUrl: '/samplePhotos/Fog in the morning.jpg',
        releaseVersion: '1.0.1',
        creationDate: 'Dec 17, 2023',
        size: '2.9 MB',
      },
    ],
  }),
  getters: {},
  actions: {},
});
